// src/components/ChessBoard/ChessPieceComponent.tsx
import React from "react";
import type { ChessGame } from "../../ChessGame";
import type { ChessPiece } from "../../ChessPiece";
import { useChessBoardContext } from "../../contexts/chess_board_context";
import { vec2, type Vector2 } from "../../Vector";

export default function ChesspieceComponent({ piece, game }: { piece: ChessPiece, game: ChessGame }) {
    const ref = React.useRef<HTMLDivElement | null>(null);
    const mouseDown = React.useRef(false);
    const { gamePosToScreenPos, screenPosToGamePos, getBoundingClientRect } = useChessBoardContext();
    const screenPos = React.useRef(gamePosToScreenPos(piece.position));

    const imageSrc = `./assets/chess_pieces/${piece.type}-${piece.color == "white" ? "w" : "b"}.svg`;

    React.useEffect(() => {
        document.addEventListener("mousemove", handleMouseMove);
        document.addEventListener("touchmove", handleMouseMove);
        document.addEventListener("mouseup", handleMouseUp);
        document.addEventListener("touchend", handleMouseUp);

        return () => {
            document.removeEventListener("mousemove", handleMouseMove);
            document.removeEventListener("touchmove", handleMouseMove);
            document.removeEventListener("mouseup", handleMouseUp);
            document.removeEventListener("touchend", handleMouseUp);
        };
    }, []);

    function updateScreenPos(pos: Vector2) {
        screenPos.current = pos;
        ref.current?.style.setProperty("translate", `${pos.x * 100}% ${pos.y * 100}%`);
    }

    function updateZIndex(zIndex: number | null) {
        ref.current?.style.setProperty("z-index", zIndex ? zIndex?.toString() : null);
    }

    function handleMouseMove(e: MouseEvent | TouchEvent) {
        if (!mouseDown.current) return;

        const clientX = "touches" in e ? e.touches[0].clientX : e.clientX;
        const clientY = "touches" in e ? e.touches[0].clientY : e.clientY;

        const rect = getBoundingClientRect();
        const x = (clientX - rect.x) / rect.width * 8;
        const y = (clientY - rect.y) / rect.height * 8;
        const newScreenPos = vec2(x - 0.5, y - 0.5);
        // setScreenPos(newScreenPos);
        updateScreenPos(newScreenPos);
    }

    function handleMouseDown() {
        mouseDown.current = true;
        updateZIndex(2);
    }

    function handleMouseUp() {
        if (!mouseDown.current) return;

        const gamePos = screenPosToGamePos(vec2(Math.floor(screenPos.current.x + 0.5), Math.floor(screenPos.current.y + 0.5)));
        game.requestMove(piece, gamePos);

        mouseDown.current = false;
        updateScreenPos(gamePosToScreenPos(piece.position));
        updateZIndex(null);
    }

    return <div ref={ref} className="chess_piece" onMouseDown={handleMouseDown} onTouchStart={handleMouseDown} style={{
        translate: `${screenPos.current.x * 100}% ${screenPos.current.y * 100}%`,
        // zIndex: mouseDown ? 2 : undefined,
    }}>
        <img src={imageSrc} draggable={false} />
    </div>
}

// src/components/ChessPiece.vue
<script setup lang="ts">
import { vec2, type Piece, type Vector2 } from '@/chess/types';
import { computed, onMounted, onUnmounted, ref, watch } from 'vue';

const props = defineProps<{
  piece: Piece,
  gamePosToScreenPos(pos: Vector2): Vector2,
  screenPosToGamePos(pos: Vector2): Vector2,
  getBoundingClientRect(): DOMRect,
}>();

const emit = defineEmits<{
  select: [],
  unselect: [newPos: Vector2],
}>();

const mouse_down = ref(false);
const screen_pos = ref(props.gamePosToScreenPos(props.piece.position));

watch(() => props.piece.position, () => {
  screen_pos.value = props.gamePosToScreenPos(props.piece.position);
})

onMounted(() => {
  window.addEventListener("mouseup", handleMouseUp);
  window.addEventListener("mousemove", handleMouseMove);
});

onUnmounted(() => {
  window.removeEventListener("mouseup", handleMouseUp);
  window.removeEventListener("mousemove", handleMouseMove);
});

function handleMouseDown() {
  mouse_down.value = true;
  emit('select');
}

function handleMouseUp() {
  if (!mouse_down.value) return;

  mouse_down.value = false;
  const gamePos = props.screenPosToGamePos(vec2(Math.floor(screen_pos.value.x + 0.5), Math.floor(screen_pos.value.y + 0.5)));
  
  emit('unselect', gamePos);
}

function handleMouseMove(event: MouseEvent) {
  if (!mouse_down.value) return;

  const rect = props.getBoundingClientRect();
  const x = (event.clientX - rect.x) / rect.width * 8;
  const y = (event.clientY - rect.y) / rect.height * 8;

  handleMovePiece(vec2(x, y));
}

function handleMovePiece(pos: Vector2) {
  screen_pos.value = vec2(pos.x - 0.5, pos.y - 0.5);
}
</script>

<template>
  <div class="piece" :class="props.piece.color, props.piece.type" @mousedown="handleMouseDown" :style="{
    translate: `${screen_pos.x * 100}% ${screen_pos.y * 100}%`,
  }"></div>
</template>

<style scoped>
.piece {
  /* background: red; */
  background-size: 100%;

  position: absolute;
  width: 12.5%;
  height: 12.5%;
}

.black.king {
  background-image: url(/assets/chess_pieces/king-b.svg);
}

.black.queen {
  background-image: url(/assets/chess_pieces/queen-b.svg);
}

.black.rook {
  background-image: url(/assets/chess_pieces/rook-b.svg);
}

.black.knight {
  background-image: url(/assets/chess_pieces/knight-b.svg);
}

.black.bishop {
  background-image: url(/assets/chess_pieces/bishop-b.svg);
}

.black.pawn {
  background-image: url(/assets/chess_pieces/pawn-b.svg);
}

.white.king {
  background-image: url(/assets/chess_pieces/king-w.svg);
}

.white.queen {
  background-image: url(/assets/chess_pieces/queen-w.svg);
}

.white.rook {
  background-image: url(/assets/chess_pieces/rook-w.svg);
}

.white.knight {
  background-image: url(/assets/chess_pieces/knight-w.svg);
}

.white.bishop {
  background-image: url(/assets/chess_pieces/bishop-w.svg);
}

.white.pawn {
  background-image: url(/assets/chess_pieces/pawn-w.svg);
}
</style>
