// src/components/ChessPiece.vue
<script setup lang="ts">
import { numberToVec2, vec2ToNumber, type Square } from '@/chess/notation';
import type { InternalPieceColor, InternalPieceType, PieceColor, PieceType } from '@/chess/piece';
import { vec2, type Vector2 } from '@/chess/vector';
import useChessBoardContext from '@/tools/use_chess_board_context';
import useWindowEvent from '@/tools/use_window_event';
import { onUpdated, ref, watch, watchEffect } from 'vue';

const props = defineProps<{
  type: PieceType,
  color: PieceColor,
  position: Square,
  canMove: boolean,
}>();

const board = useChessBoardContext();

const emit = defineEmits<{
  select: [],
  unselect: [newPos: Square],
}>();

const mouse_down = ref(false);
const screenPos = ref(board.gamePosToScreenPos(props.position));

watch([() => props.position, board.getSide], () => {
  screenPos.value = board.gamePosToScreenPos(props.position);
})

useWindowEvent("mouseup", handleMouseUp);
useWindowEvent("mousemove", handleMouseMove);
useWindowEvent("touchend", handleMouseUp)
useWindowEvent("touchmove", handleMouseMove)

function handleMouseDown() {
  if (!props.canMove) return;

  mouse_down.value = true;
  emit('select');
}

function handleMouseUp() {
  if (!mouse_down.value) return;

  mouse_down.value = false;
  const gamePos = board.screenPosToGamePos(vec2(Math.floor(screenPos.value.x + 0.5), Math.floor(screenPos.value.y + 0.5)));
  screenPos.value = board.gamePosToScreenPos(props.position);
  emit('unselect', gamePos);
}

function handleMouseMove(event: MouseEvent | TouchEvent) {
  if (!mouse_down.value) return;

  event.preventDefault();
  event.stopPropagation();

  const rect = board.getBoundingClientRect();
  const x = (("clientX" in event ? event : event.touches[0]).clientX - rect.x) / rect.width * 8;
  const y = (("clientY" in event ? event : event.touches[0]).clientY - rect.y) / rect.height * 8;

  screenPos.value = vec2(x - 0.5, y - 0.5);
}
</script>

<template>
  <div class="piece" :class="props.color, props.type, {
    selected: mouse_down,
  }" @mousedown="handleMouseDown" @touchstart="handleMouseDown" :style="{
    translate: `${screenPos.x * 100}% ${screenPos.y * 100}%`,
  }"></div>
</template>

<style scoped>
.piece {
  /* background: red; */
  background-size: 100%;

  position: absolute;
  width: 12.5%;
  height: 12.5%;
}

.selected {
  z-index: 2;
}

.piece:not(.selected) {
  transition: translate 0.1s ease-in-out;
}

.black.king {
  background-image: url(/assets/chess_pieces/king-b.svg);
}

.black.queen {
  background-image: url(/assets/chess_pieces/queen-b.svg);
}

.black.rook {
  background-image: url(/assets/chess_pieces/rook-b.svg);
}

.black.knight {
  background-image: url(/assets/chess_pieces/knight-b.svg);
}

.black.bishop {
  background-image: url(/assets/chess_pieces/bishop-b.svg);
}

.black.pawn {
  background-image: url(/assets/chess_pieces/pawn-b.svg);
}

.white.king {
  background-image: url(/assets/chess_pieces/king-w.svg);
}

.white.queen {
  background-image: url(/assets/chess_pieces/queen-w.svg);
}

.white.rook {
  background-image: url(/assets/chess_pieces/rook-w.svg);
}

.white.knight {
  background-image: url(/assets/chess_pieces/knight-w.svg);
}

.white.bishop {
  background-image: url(/assets/chess_pieces/bishop-w.svg);
}

.white.pawn {
  background-image: url(/assets/chess_pieces/pawn-w.svg);
}
</style>

// src/components/ChessPiece/index.tsx
import React from "react";
import { Vector2, gamePosToScreenPos, screenPosToGamePos } from "../Vector";
import { useChessPieceContext } from "@/context";
import ChessPieceData from "./ChessPieceData";

export enum ChessPieces {
    PAWN,
    ROOK,
    KNIGHT,
    BISHOP,
    KING,
    QUEEN,
}

export enum ChessPieceColors {
    BLACK,
    WHITE,
}

export default function ChessPiece({ data }: { data: ChessPieceData }) {
    const mouseDown = React.useRef(false);
    // const [position, setPosition] = React.useState(data.position);
    const ref = React.useRef<HTMLDivElement | null>(null);
    // const boundingClientRect = React.useRef(getBoundingClientRect());
    const { getCurrentPos, getBoundingClientRect, playingAsWhite } = useChessPieceContext();

    const mouseDownHandler = (event: React.MouseEvent<HTMLDivElement> | React.TouchEvent<HTMLDivElement>) => {
        mouseDown.current = true;
        ref.current?.style.setProperty("z-index", "2");
    }

    const mouseUpHandler = (event: React.MouseEvent<HTMLDivElement> | React.TouchEvent<HTMLDivElement>) => {
        mouseDown.current = false;
        // setPosition({ x: Math.floor(getCurrentPos().x), y: Math.floor(getCurrentPos().y) });
        const screenPos = new Vector2(Math.floor(getCurrentPos().x), Math.floor(getCurrentPos().y));
        ref.current?.style.setProperty("translate", `${screenPos.x * 100}% ${screenPos.y * 100}%`);
        data.setPosition(screenPosToGamePos(screenPos, playingAsWhite));
        ref.current?.style.setProperty("z-index", null);
    }

    const mouseMoveHandler = (event: React.MouseEvent<HTMLDivElement> | React.TouchEvent<HTMLDivElement>) => {
        // event.preventDefault();
        // event.stopPropagation();

        let clientX: number, clientY: number;
        if ('touches' in event) {
            clientX = event.touches[0].clientX;
            clientY = event.touches[0].clientY;
        } else {
            clientX = event.clientX;
            clientY = event.clientY;
        }

        const x = (clientX - getBoundingClientRect().x) / getBoundingClientRect().width * 8;
        const y = (clientY - getBoundingClientRect().y) / getBoundingClientRect().height * 8;
        if (mouseDown.current)
            ref.current?.style.setProperty("translate", `${(x - 0.5) * 100}% ${(y - 0.5) * 100}%`);
            // setPosition({ x: x - 0.5, y: y - 0.5 });
    }

    return (
        <div ref={ref} className="chess_piece" id={data.key} style={{
            // transform: `translate(${position.x * 100}%, ${position.y * 100}%)`,
            translate: `${gamePosToScreenPos(data.position, playingAsWhite).x * 100}% ${gamePosToScreenPos(data.position, playingAsWhite).y * 100}%`,
            // transform: playingAsWhite ? `translate(${position.x * 100}%, ${position.y * 100}%)` : `translate(${(7 - position.x) * 100}%, ${(7 - position.y) * 100}%)`,
        }}

        onMouseDown={mouseDownHandler}
        onTouchStart={mouseDownHandler}
        onMouseUp={mouseUpHandler}
        onTouchEnd={mouseUpHandler}
        onMouseMove={mouseMoveHandler}
        onTouchMove={mouseMoveHandler}

        >
            {/* {piece == ChessPieces.PAWN ? <img src="/pawn-w.svg" draggable="false" style={{
                width: "100%",
                height: "100%",
            }} /> : ""} */}
            {(() => {
                let src = "/pawn-w.svg";
                let pieceName = "pawn";

                switch (data.piece) {
                case ChessPieces.PAWN:
                    pieceName = "pawn";
                    break;
                case ChessPieces.ROOK:
                    pieceName = "rook";
                    break;
                case ChessPieces.BISHOP:
                    pieceName = "bishop";
                    break;
                case ChessPieces.KNIGHT:
                    pieceName = "knight";
                    break;
                case ChessPieces.KING:
                    pieceName = "king";
                    break;
                case ChessPieces.QUEEN:
                    pieceName = "queen";
                    break;
                default:
                    pieceName = "pawn";
                    break;
                }

                src = `/${pieceName}-${data.color == ChessPieceColors.BLACK ? "b" : "w"}.svg`;

                return <img src={src} draggable="false" style={{
                    width: "100%",
                    height: "100%",
                }} />;
            })()}
        </div>
    );
}
